# Originally from https://github.com/korlibs/kortemplate/blob/master/.travis.yml
matrix:
  include:
  - os: linux
    language: java
    jdk: oraclejdk8
    env: JAVA_OPTS=-Xmx2g
    cache:
      directories:
        - "~/.konan"
        - "~/.gradle/caches"
    script:
      - "./gradlew -s check build"
    after_success:
      - "./scripts/publishLinux.sh"
  - os: windows
    language: shell # java is not supported but jdk is installed
    cache:
      directories:
        - "~/.konan"
        - "~/.gradle/caches"
    script:
      - powershell -Command "cmd /c travis_win.bat"
    after_success:
      - powershell -Command "cmd /c 'set SONATYPE_USERNAME=\'$SONATYPE_USERNAME\' && set SONATYPE_PASSWORD=\'$SONATYPE_PASSWORD\' && scripts\\publishWin.bat'"
  - os: osx
    env: JAVA_OPTS=-Xmx2g
    language: java
    jdk: openjdk10
    cache:
      directories:
        - "~/.konan"
        - "~/.gradle/caches"
    before_install:
      - cp $(/usr/libexec/java_home)/lib/security/cacerts "${JAVA_HOME}/lib/security/cacerts"
    script:
      - "./gradlew -s check build"
    after_success:
      - "./scripts/publishCocoa.sh"
env:
  global:
  - secure: Bo4hp1prRs3WT86x/SIKRD1a2tbqWYVDpgqI7K4iXCTKLuVeB5nLsBCjSSCFfrPz7c186+M9jGZpLPWt8W0EV/e9ULl6l2pI5D4/4SiessJFHPyqDLJWTe2Y+em6HRs9ON9LdQ+p7UCkO0S5r2kYAcI4cj1Kp7B3phK8h3ikeYNPEjh1PnBVDuAZLFt5bOFW3/NRdPPaE2Pwn3H546AQbc740xJbmVNMpdKbXEyYDZ9yvv/iist93ary+t0z8VRxwb2b4JrJ+1As0KCeh5+ZkTyg0vZbnNwlJGvu8HWfGYLPlUtIMvueS6UBFOG93rpILGnT2d5X6avToYI/WSulQgha+dK1ippW/HfgkBMTw9IPGq/9HJrY7v3qAfa9/wLrx4KTAdmiK2UVSAxmtHxHrGkSdeLneJhdjhG5liuqSvbKs/GzUDvovicxXWimuPU4IRAN8KONZ/jvARL+GGMfxqtdMUVOuUoMvyoyXJ5dKw+elGJibp4yPDAbc2wKYkOhQIxfDwpkrY01FOrDcuunfMSQhjxNsmhZnxiacEU1Al1XFLKAY/vGGHIT9kJMRJD6Yz+UX8cT7LbKkLmYlHDLXTjA0/OLlpKUgMHafnqrK1AlwnmfAXfX0M6E1eQAM2tnCAnAIEfqLHcNUCQpUOBlZNiLwBr6rmTyzgLiklltvmE=
  - secure: pFwhcudDwFAN44Dt37nhxFgJQxVo7GiwWr4yhAH/Ly0Le73Hs6mSPxbeZcsXecZEX3zzZv++wpVDKQb2zLFC9Oi10rpwnSsqwgTgi1kcgLqOAuOLPV+V/El0M569dsLBs2tlLTvC+UrCm97LnD1SOdMj6PIzp+ItuMEBXMdNkGqhFgi6njVxgEiYKvyxE7VJI56zDu2EIO5D0wmtpzKOSXBIKgJobk9tTKp/ztRXCnG/Uj9xaIID3apV8Q4r+UkXPcGmpWUGa/xrXX6DlEIDcCYIA/C3XWZrcS4W5oc9aHeo8JuMrXk7JetDwUMUv51EorEHJy2TP4lfM5t2ChqliqEyvCSs449JLEt2RNj4SnRSEyK7EvByEqNoOCs2w2byn/HV9szXHNxMA6VUiogV8HTnIarBqyJKDsIk6hmznubS0RFYzXZos8N4NSCF7Ls2XbHlnR9uQuP52WVEGUMXMFnrnHtzvDXv3lWtjn+qut9wXRbRlI2MbOLUH3/ecZSbwp2qbdcVDhCtbAQWHwRJIdOOvOZgmOfzZ7FO20p4vzezmMqUqgTB8N2iu7v7Jo8dS6sY3Apihx3HMj6aUOWCuAwB6YTqDzk8Q+qjaHY8cSzab+rgteewRJQr/9VQQihvpLNRSrYoC+3IaIo4n3bKQncjMZwTmX6dIcXw3BA2bPI=
